# .github/workflows/update-atcoder-remaining.yml

name: Update AtCoder Remaining Points

on:
  schedule:
    - cron: '0 6 * * *'  # JST 15:00
  workflow_dispatch:

permissions:  # ← 追加
  contents: write  # ← README などに書き込むために必要

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests

      - name: Update README
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update remaining AtCoder points" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ← 自動付与されるトークン
