# .github/workflows/update-atcoder-remaining.yml

name: Update AtCoder Remaining Points

on:
  schedule:
    - cron: '0 6 * * *'  # JST 15:00
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Update README
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Update remaining AtCoder points [bot]"
          git push
